/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.social91CyclePrice;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
